name: Build hz

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: コードを取得
      uses: actions/checkout@v4

    - name: Go言語の準備
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Linux用にビルド
      working-directory: ./src   # 👈 これでActionsが自動的にsrcフォルダに入ってくれます！
      run: go build -o ../hz_linux main.go

    - name: Windows用にクロスビルド
      working-directory: ./src   # 👈 ここもsrcフォルダの中で実行させます！
      run: GOOS=windows GOARCH=amd64 go build -o ../hz_windows.exe main.go

    - name: ビルドした成果物をGitHubに保存
      uses: actions/upload-artifact@v4
      with:
        name: hz-binaries
        path: |
          hz_linux
          hz_windows.exe
